menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/1737728992
    GitHub: https://github.com/vaenow
    Rss: /atom.xml

favicon: https://avatars3.githubusercontent.com/u/1642418?v=3&s=40
logo: https://avatars0.githubusercontent.com/u/1642418?v=3&s=60

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 

# Analytics
# google-analytics:
#ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
